services:
  - type: web
    name: wise-fitness-website
    env: docker
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    dockerContext: ./
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 80
      - key: NODE_ENV
        value: production
    # Auto-deploy on push to main branch
    autoDeploy: true
